let quotes = ['The man who says he can, and the man who says he can not… Are both correct',
'Your life is what your thoughts make it',
'Real knowledge is to know the extent of one’s ignorance',
'The man who asks a question is a fool for a minute, the man who does not ask is a fool for life',
'The journey with a 1000 miles begins with one step',
'Choose a job you love, and you will never have to work a day in your life.',
'You are what you think',
'Looking at small advantages prevents great affairs from being accomplished',
'All people are the same; only their habits differ',
'Learn advidly. Question it repeatedly. Analyze it carefully. Then put what you have learned into practice intelligently',
'We have two lives, and the second begins when we realize we only have one',
'If you are the smartest person in the room, then you are in the wrong room',
'Act with kindness but do not expect gratitude',
'Worry not that no one knows you; seek to be worth knowing',
'The man who moves a mountain begins by carrying away small stones',
'When it is obvious that the goals cannot be reached, don’t adjust the goals, adjust the action steps',
'The essence of knowledge is, having it, to use it',
'One joy dispels a hundred cares',
'Anyone can find the switch after the lights are on',
'When you see a good person, think of becoming like her/him. When you see someone not so good, reflect on your own weak points',
'I slept and dreamt life is beauty, I woke and found life is duty.',
'...'
];